runtime: python39
entrypoint: gunicorn -b :$PORT mutaengine.wsgi
env_variables:
  APPENGINE_URL: https://mutaengine-test.uc.r.appspot.com
  DATABASE_URL: 'postgres://postgres:postgres@/postgres?host=/cloudsql/mutaengine-test:asia-south1:postgres'

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto
