# Generated by Django 5.1.1 on 2024-09-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_total_price_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_order_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
