# Generated by Django 5.1.1 on 2024-09-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_paypal_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approval_url',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
